### ISSUE TITLE
support for multiple users

### ISSUE THREAD

**Issue by capsudo** [cptactionhank/docker-netatalk#10]
Currently we can pass username and password via ENV vars : `AFP_USER` and `AFP_PASSWORD`. The owner for directory `/media/share` is set to `AFP_USER` in `docker-entrypoint.sh`. 

But what if I want to provide multiple shares (volumes), with different users for each ? The ENV var being unique it impossible to provide multiple users (along with their password). The only way to have multiple users is to run more docker containers of `docker-netatalk` with different ENV vars.

Would be good if there were ENV vars `AFP_USERS` and `AFP_PASSWORDS` which would actually be arrays. And owner for shares should be set per volume basis, based on which users are have access to the volumes defined (in the `afp.conf` file), not just for `/media/share`.

**Comment by cptactionhank** [comment]
Another way would be to "login" on the container and create some more users or mount a users database in the container.

Consider using `docker exec` to create more OS users to add more users
